Repository sngular/scs-multiapi-plugin, pull requests merged in 2022-07, with the labels that each got.

#92 Fix adding generated sources to project root
  README.md
  pom.xml
  src/main/java/net/coru/api/generator/plugin/OpenAsyncMojo.java
  src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
  src/main/java/net/coru/api/generator/plugin/PluginConstants.java
  src/main/java/net/coru/api/generator/plugin/asyncapi/exception/AsyncApiGeneratedSourceFolderException.java
  src/main/java/net/coru/api/generator/plugin/exception/GeneratedSourcesFolderException.java
  src/main/java/net/coru/api/generator/plugin/openapi/exception/OpenApiGeneratedSourceFolderException.java
  src/test/java/net/coru/api/generator/asyncapi/integration/test/AsyncApiGenerationTest.java
  src/test/java/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest.java
  src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/api-test.yml
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiErrorDTO.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiTestDTO.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiTestInfoDTO.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/IPublishOperation.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ISubscribeOperation.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/Producer.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/TestApi.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/TestClassName.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/event-api.yml
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/pom.xml
Labels: bug

#94 Fix missing import for enums
  pom.xml
  src/main/resources/templates/openapi/templateSchema.ftlh
  src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiEnumsGeneration/assets/ApiTestDTO.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiEnumsLombokGeneration/assets/ApiTestDTO.java
Labels: bug

#101 Update readme with OverWriteModel option
  README.md
  pom.xml
Labels: documentation

#119 updated checkout action and event on maven-pr
  .github/workflows/maven-pr.yml
Labels: enhancement

#117 115 Fix ModelClassException creation
  README.md
  pom.xml
  src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
  src/main/java/net/coru/api/generator/plugin/openapi/template/TemplateFactory.java
  src/test/java/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest.java
  src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testAllOf/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiEnumsGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiMultiGeneration/assets/ModelClassExceptionFirst.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiMultiGeneration/assets/ModelClassExceptionSecond.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiParametersWithContentGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathWithBarsGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiTagsGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testExternalRefsGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testRestClientApiGeneration/assets/ModelClassException.java
  src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testWebClientApiGeneration/assets/ModelClassException.java
Labels: bug
